language: dart
sudo: false
dart:
  - stable
  - dev
with_content_shell: false
before_script:
  - git clone https://github.com/flutter/flutter.git -b stable --depth 1
  - ./flutter/bin/flutter doctor
  - ./flutter/bin/flutter packages get
script:
  - dartanalyzer --fatal-infos --fatal-warnings ./lib/
  - dartfmt -n ./lib --set-exit-if-changed
  - pub global activate coverage
  - pub run test test/redux_undo_test.dart
  - dart --disable-service-auth-codes --enable-vm-service=8111 --pause-isolates-on-exit test/redux_undo_test.dart &
  - nohup pub global run coverage:collect_coverage --port=8111 --out=coverage.json --wait-paused --resume-isolates
  - pub global run coverage:format_coverage --lcov --in=coverage.json --out=lcov.info --packages=.packages --report-on=lib
after_success:
  - bash <(curl -s https://codecov.io/bash)