name: redux_undo
description: Make your redux store undo- and redoable. Inspired by the JS redux_undo package.

version: 0.1.0+1

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  meta: ">=1.1.1 <2.0.0"
  redux: ">=3.0.0 <4.0.0"

dev_dependencies:
  pedantic: ^1.8.0