name: redux_undo
description: Make your redux store undo- and redoable. Inspired by the JS redux_undo package.
homepage: https://github.com/michelengelen/redux_undo
maintainer: Michel Engelen (@michelengelen)
authors:
  - Flutter Community <community@flutter.zone>
  - Michel Engelen <michel@nomorejs.net>

version: 0.1.1+5

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  redux: ^4.0.0

dev_dependencies:
  test: ^1.12.0
  pedantic: ^1.9.0
  coverage: ^0.13.6
